---

- name: Clear the tty from sudoers
  raw: sed -i '/^Defaults\s*requiretty/d' /etc/sudoers

- name: Remove the standard cloud disable command
  lineinfile:
    dest: /root/.ssh/authorized_keys
    state: absent
    regexp: command\=

- name: Remove ssh keys from authorized_keys
  authorized_key:
    user: root
    key: "{{ item }}"
    state: absent
  with_items: '{{ SSH_KEYS_TO_REMOVE }}'
  when: SSH_KEYS_TO_REMOVE is defined
